# Generated by Django 4.1.2 on 2022-10-24 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergeneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('descricao', models.CharField(max_length=500, null=True)),
                ('abreviatura', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Alergéneos',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('nif', models.CharField(max_length=11, null=True)),
                ('morada', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('telefone', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='MP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'MP',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Receitas',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, null=True)),
                ('peso', models.IntegerField(null=True)),
                ('receitas', models.ManyToManyField(to='api.receita')),
            ],
            options={
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomecomercial', models.CharField(max_length=100, null=True)),
                ('codigo', models.CharField(max_length=100, null=True)),
                ('tipodeproduto', models.CharField(choices=[('Simples', 'Simples'), ('Composto', 'Composto'), ('Intermédio', 'Intermédio')], max_length=100, null=True)),
                ('descrição', models.CharField(max_length=200, null=True)),
                ('ingredientes', models.CharField(max_length=500, null=True)),
                ('proteinas', models.FloatField(null=True)),
                ('gordura', models.FloatField(null=True)),
                ('gordurassaturadas', models.FloatField(null=True)),
                ('hidratosdecarbono', models.FloatField(null=True)),
                ('acucares', models.FloatField(null=True)),
                ('minerais', models.FloatField(null=True)),
                ('fibra', models.FloatField(null=True)),
                ('humidade', models.FloatField(null=True)),
                ('namg', models.FloatField(null=True)),
                ('kjoule', models.FloatField(null=True)),
                ('kcal', models.FloatField(null=True)),
                ('criado', models.DateField(auto_now_add=True, null=True)),
                ('lastupdate', models.DateField(auto_now=True, null=True)),
                ('contemalergeneo', models.ManyToManyField(related_name='bar', to='api.alergeneo')),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fornecedor')),
                ('mp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mp')),
                ('podeconteralergeneo', models.ManyToManyField(related_name='baz', to='api.alergeneo')),
            ],
            options={
                'verbose_name_plural': 'Matérias Primas',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datadeproducao', models.DateField(auto_now_add=True, null=True)),
                ('lote', models.CharField(max_length=50, null=True)),
                ('produto', models.ManyToManyField(to='api.produto')),
            ],
            options={
                'verbose_name_plural': 'Lotes',
            },
        ),
        migrations.CreateModel(
            name='IngredientesReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(null=True)),
                ('mp', models.ForeignKey(db_column='mp', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.materiaprima')),
                ('receita', models.ForeignKey(db_column='_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.receita')),
            ],
            options={
                'verbose_name_plural': 'Receitas (Ingredientes)',
            },
        ),
        migrations.CreateModel(
            name='FornecedorContactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=11, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telefone', models.IntegerField(null=True)),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fornecedor')),
            ],
            options={
                'verbose_name_plural': 'Contactos Fornecedores',
            },
        ),
    ]
