# Generated by Django 4.1.3 on 2022-11-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestoesRegistos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questao", models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipoRegistos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("periocidade", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Registos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataregisto", models.DateTimeField()),
                ("resposta", models.BooleanField()),
                ("questao", models.ManyToManyField(to="api.questoesregistos")),
            ],
        ),
        migrations.AddField(
            model_name="questoesregistos",
            name="tipoderegisto",
            field=models.ManyToManyField(to="api.tiporegistos"),
        ),
    ]
