# Generated by Django 4.1.3 on 2022-11-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_questoesregistos_tiporegistos_registos_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questoesregistos",
            options={"verbose_name_plural": "Registos - Questões"},
        ),
        migrations.AlterModelOptions(
            name="registos",
            options={"verbose_name_plural": "Registos"},
        ),
        migrations.AlterModelOptions(
            name="tiporegistos",
            options={"verbose_name_plural": "Tipo de Registo"},
        ),
        migrations.RemoveField(
            model_name="registos",
            name="questao",
        ),
        migrations.RemoveField(
            model_name="registos",
            name="resposta",
        ),
        migrations.AddField(
            model_name="registos",
            name="tiporegisto",
            field=models.ManyToManyField(to="api.tiporegistos"),
        ),
        migrations.CreateModel(
            name="RegistosRespostas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resposta", models.CharField(max_length=50, null=True)),
                ("questao", models.ManyToManyField(to="api.questoesregistos")),
                ("registo", models.ManyToManyField(to="api.registos")),
            ],
            options={
                "verbose_name_plural": "Registos - Questões",
            },
        ),
    ]
