# Generated by Django 4.1.3 on 2022-11-07 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_questoesregistos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registosrespostas',
            options={'verbose_name_plural': 'Registos - Respostas'},
        ),
    ]
