# Generated by Django 4.1.3 on 2022-11-07 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_registosrespostas_questao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registosrespostas',
            name='tipoderegisto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tiporegistos'),
        ),
    ]
