# Generated by Django 4.1.3 on 2022-11-08 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_registosrespostas_tipoderegisto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registosrespostas',
            name='tipoderegisto',
        ),
        migrations.AddField(
            model_name='registos',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='registos',
            name='tiporegisto',
        ),
        migrations.AddField(
            model_name='registos',
            name='tiporegisto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tiporegistos'),
        ),
    ]
