# Generated by Django 4.1.3 on 2022-11-08 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_registosrespostas_tipoderegisto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registos',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='registosrespostas',
            name='questao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teste', to='api.questoesregistos'),
        ),
    ]
