# Generated by Django 4.1.3 on 2022-11-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_registos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registos',
            name='dataregisto',
            field=models.DateField(auto_now=True),
        ),
    ]
