# Generated by Django 4.1.3 on 2022-11-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_registos_dataregisto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registos',
            name='dataregisto',
            field=models.DateTimeField(),
        ),
    ]
