# Generated by Django 4.1.3 on 2022-11-08 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_registos_dataregisto'),
    ]

    operations = [
        migrations.AddField(
            model_name='registos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registos',
            name='dataregisto',
            field=models.DateField(),
        ),
    ]
