# Generated by Django 4.1.3 on 2022-11-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_registos_created_alter_registos_dataregisto'),
    ]

    operations = [
        migrations.AddField(
            model_name='registos',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
