# Generated by Django 4.1.3 on 2022-11-15 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_registos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registos',
            name='tiporegisto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='names', to='api.tiporegistos'),
        ),
    ]
